name: 7T-Project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blosc=1.21.3=h313beb8_0
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py312h313beb8_8
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.8.30=hf0a4a13_0
  - certifi=2024.8.30=py312hca03da5_0
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.2=h313beb8_0
  - fonttools=4.51.0=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - imagecodecs=2023.1.23=py312h75b721f_1
  - imageio=2.33.1=py312hca03da5_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.0=py312hca03da5_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.27.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=py312hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h81bd7bf_0
  - jxrlib=1.1=h1a28f6b_2
  - kiwisolver=1.4.4=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lazy_loader=0.4=py312hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libavif=0.11.1=h80987f9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h3e2b118_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.13.1=h0b34f26_2
  - libxslt=1.1.41=hf4d3faa_0
  - libzlib=1.2.13=hfb2fe0b_6
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lxml=5.2.1=py312h1d4350b_1
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.9.2=py312h1f38498_1
  - matplotlib-base=3.9.2=py312h2df2da3_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=py312hca03da5_0
  - nibabel=5.2.1=pyha770c72_0
  - nilearn=0.10.4=pyhd8ed1ab_0
  - nptyping=2.5.0=pyhd8ed1ab_1
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.3.1=h8359307_3
  - packaging=24.1=py312hca03da5_0
  - pandas=2.2.2=py312hd77ebd4_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=py312hca03da5_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h80987f9_0
  - pip=24.2=py312hca03da5_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h7e5086c_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=5=hd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynrrd=1.0.0=pyhc1e730c_0
  - pyparsing=3.1.2=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312hca03da5_0
  - pyzmq=25.1.1=py312h2105c20_2
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py312hca03da5_0
  - scikit-image=0.23.2=py312hd77ebd4_0
  - scikit-learn=1.5.1=py312hd77ebd4_0
  - scipy=1.13.1=py312ha409365_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=72.1.0=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h313beb8_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py312ha86b861_0
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tifffile=2023.4.12=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.1=py312h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py312hca03da5_0
  - typish=1.9.3=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_0
  - urllib3=2.2.2=py312hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zeromq=4.3.5=h313beb8_0
  - zfp=1.0.0=h313beb8_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.5=hd90d995_2
  - pip:
      - itk==5.4.0
      - itk-core==5.4.0
      - itk-filtering==5.4.0
      - itk-io==5.4.0
      - itk-numerics==5.4.0
      - itk-registration==5.4.0
      - itk-segmentation==5.4.0
prefix: /Users/ruili/miniconda3/envs/7T-Project-env
